version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      OTEL_TRACES_EXPORTER: console
      OTEL_METRICS_EXPORTER: console
      OTEL_LOGS_EXPORTER: console
